mysql:
  host: localhost
  port: 3306
  ssl: false
  autoreconnect: true
  username: username
  password: password
  database: database
  
options:
  tag:
    messages:
      no-permission: "&c&lCommand Under Development!"
      reload-config: "&aConfig Reloaded."
  prefix: "&e&lMW &r"